package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_FinancialEntityType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_FinancialEntityType() {
    super(0x437c9db1d8f44db9L, 0xb294bc781192d511L, 0x713163e567bb5253L, "FinancialEntityType", "r:1bd05ee4-1cfd-460a-b7cb-4e1ec89d275e(NewLanguage.structure)/8156410237083669075");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Bank_0 = new EnumerationDescriptor.MemberDescriptor("Bank", "Bank", 0x713163e567bb5254L, "r:1bd05ee4-1cfd-460a-b7cb-4e1ec89d275e(NewLanguage.structure)/8156410237083669076");
  private final EnumerationDescriptor.MemberDescriptor myMember_InvestmentFirm_0 = new EnumerationDescriptor.MemberDescriptor("InvestmentFirm", "InvestmentFirm", 0x713163e567bb585dL, "r:1bd05ee4-1cfd-460a-b7cb-4e1ec89d275e(NewLanguage.structure)/8156410237083670621");
  private final EnumerationDescriptor.MemberDescriptor myMember_CreditUnion_0 = new EnumerationDescriptor.MemberDescriptor("CreditUnion", "CreditUnion", 0x713163e567c55363L, "r:1bd05ee4-1cfd-460a-b7cb-4e1ec89d275e(NewLanguage.structure)/8156410237084324707");
  private final EnumerationDescriptor.MemberDescriptor myMember_Insurance_0 = new EnumerationDescriptor.MemberDescriptor("Insurance", "Insurance", 0x713163e567bb5860L, "r:1bd05ee4-1cfd-460a-b7cb-4e1ec89d275e(NewLanguage.structure)/8156410237083670624");
  private final EnumerationDescriptor.MemberDescriptor myMember_Cooperative_0 = new EnumerationDescriptor.MemberDescriptor("Cooperative", "Cooperative", 0x713163e567bd4eadL, "r:1bd05ee4-1cfd-460a-b7cb-4e1ec89d275e(NewLanguage.structure)/8156410237083799213");
  private final EnumerationDescriptor.MemberDescriptor myMember_Others_0 = new EnumerationDescriptor.MemberDescriptor("Others", "Others", 0x713163e567c5439aL, "r:1bd05ee4-1cfd-460a-b7cb-4e1ec89d275e(NewLanguage.structure)/8156410237084320666");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x437c9db1d8f44db9L, 0xb294bc781192d511L, 0x713163e567bb5253L, 0x713163e567bb5254L, 0x713163e567bb585dL, 0x713163e567c55363L, 0x713163e567bb5860L, 0x713163e567bd4eadL, 0x713163e567c5439aL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Bank_0, myMember_InvestmentFirm_0, myMember_CreditUnion_0, myMember_Insurance_0, myMember_Cooperative_0, myMember_Others_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Bank":
        return myMember_Bank_0;
      case "InvestmentFirm":
        return myMember_InvestmentFirm_0;
      case "CreditUnion":
        return myMember_CreditUnion_0;
      case "Insurance":
        return myMember_Insurance_0;
      case "Cooperative":
        return myMember_Cooperative_0;
      case "Others":
        return myMember_Others_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
