package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_PartyTypes extends EnumerationDescriptorBase {

  public EnumerationDescriptor_PartyTypes() {
    super(0x437c9db1d8f44db9L, 0xb294bc781192d511L, 0x713163e567bdbc8eL, "PartyTypes", "r:1bd05ee4-1cfd-460a-b7cb-4e1ec89d275e(NewLanguage.structure)/8156410237083827342");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_idividual_0 = new EnumerationDescriptor.MemberDescriptor("idividual", "idividual", 0x713163e567bdbc8fL, "r:1bd05ee4-1cfd-460a-b7cb-4e1ec89d275e(NewLanguage.structure)/8156410237083827343");
  private final EnumerationDescriptor.MemberDescriptor myMember_organization_0 = new EnumerationDescriptor.MemberDescriptor("organization", "organization", 0x713163e567bdbc96L, "r:1bd05ee4-1cfd-460a-b7cb-4e1ec89d275e(NewLanguage.structure)/8156410237083827350");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x437c9db1d8f44db9L, 0xb294bc781192d511L, 0x713163e567bdbc8eL, 0x713163e567bdbc8fL, 0x713163e567bdbc96L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_idividual_0, myMember_organization_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "idividual":
        return myMember_idividual_0;
      case "organization":
        return myMember_organization_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
